export const ROUTES = {
  HOME: '/',
  MENU: '/menu',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDER_DETAILS: '/orders/:orderId',
  PROFILE: '/profile',
  WISHLIST: '/wishlist',
  ADMIN: '/admin',
  RESTAURANTS: '/restaurants',
  RESTAURANT_DETAILS: '/restaurants/:id',
  NOT_FOUND: '*',
};